nblockchain/geewallet

src/GWallet.Frontend.Console/Program.fs
Password confirmation returned successful when password was wrong, and returned with error when password was right.
=> Frontend.Console: fix password confirm problem

GWallet.Backend.nuspec, src/GWallet.Backend.Tests.Unit/GWallet.Backend.Tests.Unit.fsproj, src/GWallet.Backend.Tests.Unit/packages.config, src/GWallet.Backend/GWallet.Backend.fsproj, src/GWallet.Backend/UtxoCoin/Lightning/Network.fs, src/GWallet.Backend/UtxoCoin/TorOperations.fs, src/GWallet.Backend/packages.config
Catch the NOnionException after the Retries have finished and the problem still exists. We catch the exception and return an error.
Fixes https://github.com/nblockchain/geewallet/issues/181 
Fixes https://github.com/nblockchain/geewallet/issues/182
=> Backend(LN): catch NOnionException TorOperations

src/GWallet.Backend.Tests/AsyncExtensions.fs, src/GWallet.Backend/FSharpUtil.fs
Fixed bug in Async.MixedParallel* functions when
resulting computation would wait for all sub-computations to
finish, even if one of them threw exception.
Now exception will propagate immediately.
Added MixedParallel4 function. It was added with RGS support,
and decision was made to fix it too rather than have correct
2 and 3 argument variants and incorrect 4-argument one.
Added tests for all MixedParallel* functions.
=> Async.MixedParallel fix

.github/workflows/CI.yml
We now use a script in conventions repo so that the invocation
approach can be defined there (because we've had to
downgrade to a previous version and we don't want all
consumers of conventions repo to need to know about this,
they can just call this script).
=> GitHubCI: fix commitlint invocation

.github/workflows/CI.yml
We keep getting CI errors because apt encounters (e.g. [1]) 503 HTTP error codes when trying to retrieve packages from the apt source. Example:
```
Get:288 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 npm all 6.14.4+ds-1ubuntu2 [583 kB]
Fetched 11.0 MB in 10s (1142 kB/s)
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/n/node-form-data/node-form-data_3.0.0-2_all.deb  503  Service Unavailable [IP: 52.252.75.106 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```
By switching to a vanilla VM, we'll likely dodge this problem because the vanilla OS shouldn't have azure apt repos configured by default.
NOTE: after merging this, we get some scary warnings when running …
=> GitHubCI(conventions): move to vanilla VM

src/GWallet.Backend/Config.fs, src/GWallet.Backend/GWallet.Backend.fsproj
This commit removes the now unused dependency to
Xamarin.Essentials which was introduced in https://github.com/nblockchain/geewallet/commit/97d580050c8baac3b0cebc602fa5fb57c92014b8 and went out of use in https://github.com/nblockchain/geewallet/commit/9dd3f9e65ec830850cf12ed1fa91d1799518b3b1.
For future references adding XE to Backend can cause problems with MAUI because it adds Xamarin.Android.Support.V4 as dependency which conflicts with MAUI's AndroidX dependency.
=> Backend: remove unused XE dependency

src/GWallet.Backend/GWallet.Backend.fsproj, src/GWallet.Backend/packages.config
This commit updates the JsonRpcSharp library which
uses an older version of FSharp.Core.
This fixes the FSharp.Core version conflict
problem caused by [1] which was trying to fix
integration tests in [2].
[1]
https://github.com/nblockchain/geewallet/commit/3bcde0b8ed24bc91d498a34bf887b5dd08b53af3
[2]
https://github.com/nblockchain/geewallet/commit/9392215bfa6c0f625ddce6423b3bf77a0dea8558
=> Backend: pin FSharp.Core in JsonRpcSharp

src/GWallet.Backend/GWallet.Backend-legacy.fsproj
Using the same folder for two project that use different frameworks, causes problems due to incompatible caches in obj folder, this commit fixes that by moving the cache folder for the legacy version.
=> GWallet.Backend: move legacy obj path

src/GWallet.Backend.Tests/packages.config
While Fsdk is referenced in fsproj file it was not present in packages.config, it did not cause red CI because Fsdk was referenced in another packages.config file.
=> Backend.Tests: add missing packages.config ref

src/GWallet.Backend/Account.fs, src/GWallet.Backend/Ether/EtherAccount.fs, src/GWallet.Backend/Exceptions.fs, src/GWallet.Backend/UtxoCoin/UtxoCoinAccount.fs, src/GWallet.Frontend.Console/Program.fs
This prevents any future bug to cause unreasonable fees.
=> Backend: make sure fee is less than out

src/GWallet.Backend/Ether/EtherAccount.fs
This commit fixes crash when balance is
less then fees when sweeping.
=> Backend(Ether): fix sweep when high fees

geewallet.sln
This commit fixes this error when restoring geewallet.sln projects:
```
C:\geewallet\geewallet.sln : Solution file error MSB5009:
Error parsing the project "Fsdk" section with GUID: "{6EE0754
1-91A1-42C2-A21F-2809BBDC2F50}". It is nested under
"{CE79AB9D-0FB9-4606-B7C6-A78C0858CC54}" but that project is not fo
und in the solution.
```
=> sln: remove fsdk nested proj from solution

scripts/fsxHelper.fs, scripts/make.fsx, scripts/make.sh, scripts/sanitycheck.fsx, src/GWallet.Frontend.XF.Android/GWallet.Frontend.XF.Android.fsproj, src/GWallet.Frontend.XF.Android/packages.config, src/GWallet.Frontend.XF.Gtk/GWallet.Frontend.XF.Gtk.fsproj, src/GWallet.Frontend.XF.Gtk/packages.config, src/GWallet.Frontend.XF.Mac/GWallet.Frontend.XF.Mac.fsproj, src/GWallet.Frontend.XF.Mac/packages.config, src/GWallet.Frontend.XF.iOS/GWallet.Frontend.XF.iOS.fsproj, src/GWallet.Frontend.XF.iOS/packages.config
Closes #229
Closes #230
Closes #231 
Closes #232
=> Fix nuget sanitycheck

src/GWallet.Backend.Tests/Deserialization.fs, src/GWallet.Backend.Tests/StratumParsing.fs, src/GWallet.Backend/UtxoCoin/ElectrumClient.fs, src/GWallet.Backend/UtxoCoin/StratumClient.fs
This PR fixes the deserialization error happening
when returned error is a simple string instead of an object
containing errorCode and errorMsg.
=> Fix error deserialization bug

scripts/bump.fsx, src/GWallet.Backend.Tests/Deserialization.fs, src/GWallet.Backend.Tests/GWallet.Backend.Tests.fsproj, src/GWallet.Backend.Tests/MarshallingData.fs, src/GWallet.Backend.Tests/MetaMarshalling.fs, src/GWallet.Backend.Tests/Serialization.fs, src/GWallet.Backend.Tests/data/signedAndFormattedBtcTransaction.json, src/GWallet.Backend.Tests/data/signedAndFormattedEtherTransaction.json, src/GWallet.Backend.Tests/data/signedAndFormattedSaiTransaction.json, src/GWallet.Backend.Tests/data/unsignedAndFormattedBtcTransaction.json, src/GWallet.Backend.Tests/data/unsignedAndFormattedEtherTransaction.json, src/GWallet.Backend.Tests/data/unsignedAndFormattedSaiTransaction.json, src/GWallet.Backend/Account.fs, src/GWallet.Backend/GWallet.Backend.fsproj, src/GWallet.Backend/Marshalling.fs
Fixes https://github.com/nblockchain/geewallet/issues/242
=> Backend(,Backend.Tests): improve marshalling to fix crash

src/GWallet.Frontend.Console/Program.fs, src/GWallet.Frontend.Console/UserInteraction.fs
Show progress when checking balances so that we can know which currency is the slow one.
Fixes #245
=> Frontend.Console: show progress when checking balances

src/GWallet.Backend/Account.fs
Add new exception type that wraps ResultInconsistencyException when checking for balances and includes currency for which the operation has failed.
Fixes https://github.com/nblockchain/geewallet/issues/246
=> Backend: new exn type that includes currency

src/GWallet.Backend.Tests/FaultTolerance.fs, src/GWallet.Backend/Account.fs, src/GWallet.Backend/FaultTolerantParallelClient.fs
Closes https://github.com/nblockchain/geewallet/issues/250
=> Backend: improve inconsistency edge case

src/GWallet.Frontend.XF.Android/GWallet.Frontend.XF.Android.fsproj, src/GWallet.Frontend.XF.Gtk/GWallet.Frontend.XF.Gtk.fsproj, src/GWallet.Frontend.XF.Mac/GWallet.Frontend.XF.Mac.fsproj, src/GWallet.Frontend.XF.iOS/GWallet.Frontend.XF.iOS.fsproj
Fix project references in Fronend.XF.*.fsproj files by adding `<Project>` element with project guid to each project reference. This is needed to avoid "error  : Unrecognized Guid format" error when loading projects in Visual Studio 2022.
=> Frontend.XF.*: fix references in .fsproj files

src/GWallet.Backend.Tests/Deserialization.fs, src/GWallet.Backend.Tests/MarshallingData.fs, src/GWallet.Backend/Account.fs, src/GWallet.Backend/Config.fs, src/GWallet.Backend/Ether/EtherAccount.fs, src/GWallet.Backend/Marshalling.fs, src/GWallet.Backend/Transaction.fs, src/GWallet.Backend/UtxoCoin/UtxoCoinAccount.fs, src/GWallet.Frontend.Console/Presentation.fs, src/GWallet.Frontend.Console/Program.fs, src/GWallet.Frontend.XF/SendPage.xaml.fs
This change also reduces a bit of primitive obsession (i.e. string vs BitcoinAddress) to make the code less "stringly-typed" lol.
This should have been done in [1] but was an oversight on my part when reviewing.
[1] https://github.com/nblockchain/geewallet/pull/211
=> Backend/UtxoCoin: support native-segwit with cold storage

src/GWallet.Backend/GWallet.Backend-legacy.fsproj, src/GWallet.Backend/GWallet.Backend.fsproj, src/GWallet.Backend/packages.config
The underlying reason to upgrade these dependencies was to actually upgrade their transitive dependencies (mainly the one called System.IO.Pipelines), with the hope that it might fix https://github.com/nblockchain/geewallet/issues/258 . In case it does not, we will create a new bug (hopefully with new stacktrace).
Closes https://github.com/nblockchain/geewallet/issues/258
=> Backend: upgrade JsonRpcSharp & Nethereum

src/GWallet.Frontend.XF/WelcomePage.xaml, src/GWallet.Frontend.XF/WelcomePage.xaml.fs
Use Grid instead of StackLayout so that our upcoming Maui app's layout is fixed. See [1] for more info.
This commit was extracted from the MAUI PR [2].
[1] https://github.com/dotnet/maui/wiki/Xamarin.Forms----MAUI.Controls-Layout-Differences#stacklayout
[2] https://github.com/nblockchain/geewallet/pull/241
Co-authored-by: webwarrior-ws `<reg@webwarrior.ws>`
=> Frontend.XF(WelcomePage): change layout to Grid

src/GWallet.Frontend.XF/BalancesPage.xaml, src/GWallet.Frontend.XF/BalancesPage.xaml.fs, src/GWallet.Frontend.XF/Controls/CircleChartView.fs, src/GWallet.Frontend.XF/LoadingPage.xaml, src/GWallet.Frontend.XF/LoadingPage.xaml.fs, src/GWallet.Frontend.XF/PairingFromPage.xaml, src/GWallet.Frontend.XF/PairingFromPage.xaml.fs, src/GWallet.Frontend.XF/PairingToPage.xaml, src/GWallet.Frontend.XF/PairingToPage.xaml.fs, src/GWallet.Frontend.XF/ReceivePage.xaml, src/GWallet.Frontend.XF/ReceivePage.xaml.fs, src/GWallet.Frontend.XF/SendPage.xaml, src/GWallet.Frontend.XF/SendPage.xaml.fs, src/GWallet.Frontend.XF/WelcomePage2.xaml, src/GWallet.Frontend.XF/WelcomePage2.xaml.fs
1. Use Grid instead of StackLayout as root layout so that in Maui the layout is the same as in Xamarin.Forms (was not true with StackLayout).
2. Remove ZXingBarcodeImageView.BarcodeOptions from xaml files as MAUI version of ZXing library doesn't support this tag in xaml anymore.
=> Preparations before move to MAUI

src/GWallet.Backend/Ether/EtherExceptions.fs, src/GWallet.Backend/Ether/EtherServer.fs, src/GWallet.Backend/ServerManager.fs
Introduce WeirdNullResponseException type and raise it when response for balance request for Ethereum returns json with "result" field value of `null`. This way server will be marked as faulty instead of crashing the application.
Fixes https://github.com/nblockchain/geewallet/issues/282
=> Backend: handle null response from Eth server

src/GWallet.Backend/Ether/EtherServer.fs
Handle HTTP error 410 (gone) in error handling code (raise ServerUnavailableException).
=> Backend/Ether: handle HTTP error 410

.github/workflows/CI.yml
- Changed MacOS version used in CI to 13, as version 12 got
deprecated [1] and causes the jobs to be cancelled.
- Installed specific versions of Xamarin.iOS & Xamarin.Android
(the same as on MacOS 12), because MacOS 13 doesn't come with
Xamarin preinstalled, and build fails with error:
```
/Users/runner/work/geewallet/geewallet/src/GWallet.Frontend.XF.iOS/GWallet.Frontend.XF.iOS.fsproj(92,11): error MSB4226: The imported project "/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/xbuild/Xamarin/iOS/Xamarin.iOS.FSharp.targets" was not found. Also, tried to find "Xamarin/iOS/Xamarin.iOS.FSharp.targets" in the fallback search path(s) for $(MSBuildExtensionsPath) - "/Library/Frameworks/Mono.framework/External/xbuild/" . These search paths are defined in …
```
=> GithubCI: switch to MacOS 13
